name: Dockerized URL Shortener CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  url-ci:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/url-shortener:v1 .

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/url-shortener:v1